### ISSUE TITLE
"An error occurred while installing DokuWik"

### ISSUE THREAD

**Issue by sleep2death** [bitnami/bitnami-docker-dokuwiki#103]
### Name and Version

bitnami/dokuwiki:20200729

### What steps will reproduce the bug?

```yaml
dokuwiki:
       image: bitnami/dokuwiki:20200729
       restart: always
       volumes:
           - ./data/dokuwiki:/bitnami/dokuwiki
         environment:
           - DOKUWIKI_USERNAME=xxx
           - DOKUWIKI_PASSWORD=xxx
           - DOKUWIKI_EMAIL=xxx
           - DOKUWIKI_WIKI_NAME=DokuWiki
```

### What is the expected behavior?

Should be working...

### What do you see instead?

See the error log from docker:
```
kuwiki_1            | dokuwiki 07:54:33.32 Welcome to the Bitnami dokuwiki container
dokuwiki_1            | dokuwiki 07:54:33.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
dokuwiki_1            | dokuwiki 07:54:33.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
dokuwiki_1            | dokuwiki 07:54:33.32
dokuwiki_1            | dokuwiki 07:54:33.32 INFO  ==> ** Starting DokuWiki setup **
dokuwiki_1            | realpath: /bitnami/apache/conf: No such file or directory
dokuwiki_1            | dokuwiki 07:54:33.37 INFO  ==> Configuring PHP options
dokuwiki_1            | dokuwiki 07:54:33.46 INFO  ==> Configuring file permissions for DokuWiki
dokuwiki_1            | dokuwiki 07:54:33.47 INFO  ==> Starting apache in background
dokuwiki_1            | [Sat Feb 12 07:54:33.568841 2022] [ssl:warn] [pid 63] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1            | [Sat Feb 12 07:54:33.569332 2022] [ssl:warn] [pid 63] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
dokuwiki_1            | dokuwiki 07:54:38.60 INFO  ==> apache started
dokuwiki_1            | dokuwiki 07:54:38.70 ERROR ==> An error occurred while installing DokuWiki
```
