### ISSUE TITLE
install.php still present after install

### ISSUE THREAD

**Issue by nqb** [bitnami/bitnami-docker-dokuwiki#35]
Hello,

With latest image, after container init, I notice that `/opt/bitnami/dokuwiki/install.php` is still present.

Could you remove this file in next release ?

**Comment by tompizmor** [comment]
Hello @nqb,

I've tried to reproduce the issue but in my case the `/opt/bitnami/dokuwiki/install.php` is not present after the initialization. 

If you check the content of `/root/.nami/components/com.bitnami.dokuwiki/main.js` file, you can see the actions run to initialize DokuWiki. Please note that the following line should be executed:

```
$file.delete('install.php');
```

The only thing I can imagine for the file to be present after the container inits, is that there was an error before deleting the file.

**Comment by nqb** [comment]
Hello @tompizmor,

You are true. I can't reproduce when creating a new container from latest image. 

However, I notice this strange behavior after upgrading from 0.20170219.201708232029-r0 to  0.20170219.201708232029-r1 release with upgrade instructions found here : https://hub.docker.com/r/bitnami/dokuwiki/

Steps to reproduce : 

1. Init a container with 0.20170219.201708232029-r0 release : install.php is remove after install
2. Follow upgrade instructions in https://hub.docker.com/r/bitnami/dokuwiki/
3. Start container : install.php is present in `/opt/bitnami/dokuwiki/install.php`

docker-compose.yml file used : 
```
version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    labels:
      kompose.service.type: nodeport
    network_mode: bridge
    restart: always
    ports:
      - '83:80'
    env_file: init_dokuwiki
    volumes:
      - 'dokuwiki_data:/bitnami'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
volumes:
    dokuwiki_data:
      driver: local
```

init_dokuwiki file used : 
```
DOKUWIKI_USERNAME=admin
DOKUWIKI_PASSWORD=secret
```
