### ISSUE TITLE
cant login when using traefik?

### ISSUE THREAD

**Issue by thepenguinthatwants** [bitnami/bitnami-docker-dokuwiki#60]
Hi!

I tried this on traefik docker-compose and there is no login possibilities. Any ways to debug? docker-compose logs didn't show any errors

```
version: '3'
services:


  dokuwiki:
    image: bitnami/dokuwiki:latest
    restart: always
    volumes:
    - '/home/someone/dokuwiki:/bitnami'
    networks:
      - web
    ports:
      - "8081:80"
    environment:
      - DOKUWIKI_USERNAME=man
      - DOKUWIKI_PASSWORD=man
      - DOKUWIKI_WIKI_NAME=man
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:dokuwiki.example.xyz"

networks:
  web:
    external: true

```
