### ISSUE TITLE
Can not create a volume for /certs to use custom certificates

### ISSUE THREAD

**Issue by amercat37** [bitnami/bitnami-docker-dokuwiki#66]
Trying to map a volume to /certs to use custom certificates.

docker-compose:

```
version: '3.7'

services:
  web:
    image: bitnami/dokuwiki:0.20180422.201901061035-debian-9-r258
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: c:/volumes/dokuwiki/web/bitnami
        target: /bitnami
      - type: bind
        source: c:/volumes/dokuwiki/web/certs
        target: /certs
    ports:
      - "4443:443"
      - "4080:80"
    environment:
      - DOKUWIKI_USERNAME=admin
      - DOKUWIKI_FULL_NAME=Administrator
      - DOKUWIKI_PASSWORD=Password1
      - DOKUWIKI_EMAIL=example@example.com
      - DOKUWIKI_WIKI_NAME=Bitnami DokuWiki
```

Deploying with:
`docker stack deploy -c docker-compose.yml dokuwiki`

Log:
```
nami INFO Initializing apache
nami INFO apache successfully initialized
nami INFO Initializing php
nami INFO php successfully initialized
nami INFO Initializing dokuwiki
dokuwik INFO Passing wizard, please be patient
dokuwik INFO
dokuwik INFO ########################################################################
dokuwik INFO Installation parameters for dokuwiki:
dokuwik INFO username: admin
dokuwik INFO user fullname: Administrator
dokuwik INFO Password: **********
dokuwik INFO Email: example@example.com
dokuwik INFO Wiki Name: Bitnami DokuWiki
dokuwik INFO (Passwords are not shown for security reasons)
dokuwik INFO ########################################################################
dokuwik INFO
nami INFO dokuwiki successfully initialized
INFO ==> Starting dokuwiki...
127.0.0.1 - - [11/Nov/2019:18:50:00 +0000] "GET /install.php HTTP/1.1" 200 10239
127.0.0.1 - - [11/Nov/2019:18:50:00 +0000] "POST /install.php HTTP/1.1" 200 6038
```

I've tried on windows and ubuntu 18 with the same results. My windows docker version is:
Docker version 19.03.4, build 9013bf5

I would expect to see server.crt and server.pem in my volume folder, however, the folder remains empty. I have tried the multiple versions of bitnami dokuwiki.

`bitnami/dokuwiki:0.20180422.201901061035-debian-9-r258`
`bitnami/dokuwiki:0.20180422.201901061035-ol-7-r301`
`bitnami/dokuwiki:latest`

Thanks
