### ISSUE TITLE
UID 1001 already taken on host

### ISSUE THREAD

**Issue by Ronaldvr** [bitnami/bitnami-docker-dokuwiki#80]
While I applaud the use of non-root container, the choice of the 1001 user is somewhat awkward, since that UID is usually already taken on the host system, and thus will create conflicts. It may be too late now, but for others it might be useful to choose another UID (in the 60000s or even higher perhaps)

**Comment by miguelaeh** [comment]
Hi @Ronaldvr ,
Thank you for the suggestions. Could you describe which are the conflicts you are getting? In principle, the container's UIDs should e independent from the host UIDs.

**Comment by Ronaldvr** [comment]
>  In principle, the container's UIDs should e independent from the host UIDs.

Actually no: this is exactly why container processes should not run as root from https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf:

>  So you can’t have different users with the same uid inside different containers. That’s because the username (and group names) that show up in common linux tools aren’t part of the kernel, but are managed by external tools (/etc/passwd, LDAP, Kerberos, etc). So, you might see different usernames, but you can’t have different privileges for the same uid/gid, even inside different containers. This can seem pretty confusing at first, so let’s illustrate it with a few examples:

**Comment by miguelaeh** [comment]
Hi @Ronaldvr ,
It is an interesting article. At the end I can also se this:
> The better solution is to start containers with a known uid using the--user(you can use a username also, but remember that it’s just a friendlier way of providing a uid from the host’s username system), and then limiting access to the uid on the host that you’ve decided the container will run as.

So, having the user 1001 as our Dockerfiles have should no be an issue, but you should take it into account if you have a user using the UID 1001 into your host system. We could change it to any other user but the possibility that that user is being used will always exist.
Anyway, I will comment this with the rest of the team, just to check what they think.

**Comment by miguelaeh** [comment]
Thank you @Ronaldvr for sharing that link, it has useful information.
I also want to share that our containers are ready to work with any UID since we create them being careful about being able to use them in platforms like Openshift, which uses random UIDs. So, it is possible to change the UID to whichever is needed in each personal case.

**Comment by damufo** [comment]
Would it be possible to add a variable to be able to define the UID at the time of creating the docker?
```
environment:
      - UID=1001
```

**Comment by miguelaeh** [comment]
Hi @damufo ,
you can use the `--user` flag if using `docker` or the following if using docker-compose:
```
- user: <UID>
```

**Comment by damufo** [comment]
Oh!! very thanks!!

**Comment by Ronaldvr** [comment]
Oh wow! can we mark this as resolved then in stead of stale?

**Comment by damufo** [comment]
Hello:

This not work for me. 
Add
 - 'USER=1000'

```
version: '2'
services:
  dokuwiki:
    container_name: dokuwiki
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - 'USER=1000'
      - 'DOKUWIKI_USERNAME=damufo'
      - 'DOKUWIKI_FULL_NAME=Informático FEGAN'
      - 'DOKUWIKI_PASSWORD=dic0t0cU'
      - 'DOKUWIKI_EMAIL=informatico@fegan.org'
      - 'DOKUWIKI_WIKI_NAME=FEGAN DokuWiki'

    volumes:
#      - 'dokuwiki_data:/bitnami/dokuwiki'
      - './dokuwiki_folder:/bitnami/dokuwiki'
#volumes:
#  dokuwiki_data:
#    driver: local

```

```
dokuwiki    | dokuwiki 13:10:40.42 INFO  ==> Persisting DokuWiki installation
dokuwiki    | cp: cannot create directory '/bitnami/dokuwiki/data': Permission denied
dokuwiki exited with code 1

```

**Comment by miguelaeh** [comment]
Hi @damufo ,
It is not an env var, you just need to override the container user since the image is prepared to work with any user:
```
version: '2'
services:
  dokuwiki:
    container_name: dokuwiki
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    ports:
      - '8081:8080'
      - '443:8443'
    user: '1000'
    volumes:
#      - 'dokuwiki_data:/bitnami/dokuwiki'
      - './dokuwiki_folder:/bitnami/dokuwiki'
#volumes:
#  dokuwiki_data:
#    driver: local
```

> NOTE: be sure to change the permissions of your local folder to `1000` to avoid permissions error
