### ISSUE TITLE
Cert-Error behind Proxy

### ISSUE THREAD

**Issue by Limbolindi** [bitnami/bitnami-docker-dokuwiki#92]
docker-compose.yml
```
version: '3.5'
services: 
    wiki.myhomepage.it:
        image: bitnami/dokuwiki:latest
        container_name: wiki
        restart: always
        ports:
            - 45100:8443
        volumes:
            - /opt/data/dokuwiki/:/bitnami/dokuwiki
        healthcheck:
            test: curl -f http://localhost || exit 1
            interval: 120s
            timeout: 60s
            retries: 3
            start_period: 120s
networks: 
    default:
        name: dokuwiki_network

```

docker-compose versio
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

docker-compose logs
```
wiki                    | dokuwiki 09:18:47.38 Welcome to the Bitnami dokuwiki container
wiki                    | dokuwiki 09:18:47.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
wiki                    | dokuwiki 09:18:47.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
wiki                    | dokuwiki 09:18:47.38 
wiki                    | dokuwiki 09:18:47.46 INFO  ==> ** Starting DokuWiki setup **
wiki                    | dokuwiki 09:18:47.49 INFO  ==> Configuring PHP options
wiki                    | dokuwiki 09:18:47.56 INFO  ==> Configuring file permissions for DokuWiki
wiki                    | dokuwiki 09:18:47.56 INFO  ==> Starting apache in background
wiki                    | [Mon Mar 08 09:18:47.640340 2021] [ssl:warn] [pid 55] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
wiki                    | [Mon Mar 08 09:18:47.640877 2021] [ssl:warn] [pid 55] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name

```

```
docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```
nginx - proxy conf

```
server {
	listen 80;
	listen [::]:80;
	server_name wiki.myhomepage.it;
	return 301 https://$server_name$request_uri;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name wiki.myhomepage.it;

	ssl_protocols TLSv1.1 TLSv1.2;
	ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA HIGH !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";

	ssl_certificate /etc/letsencrypt/live/wiki.myhomepage.it/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/wiki.myhomepage.it/privkey.pem; # managed by Certbot

	location / {
		add_header Strict-Transport_Security "max-age=31536999; includeSubDomains; preload";
		add_header Referrer-Policy "same-origin";
		add_header X-XSS-Protection "1; mode=block";
		add_header X-Frame-Options "SAMEORIGIN";
		proxy_cookie_path / "/; secure; HttpOnly";

		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_pass http://127.0.0.1:45100;

		#client_max_body_size 256M;
	}
}

```

So please, what is wrong with my settings?
