### ISSUE TITLE
How to use let's encrypt certificates with this image?

### ISSUE THREAD

**Issue by cl3b34** [bitnami/bitnami-docker-dokuwiki#96]
I'm using the latest version of this image, running on docker on an AWS Lightsail VPS instance (AWS Linux).

I'm trying to create a let's encrypt certificate and configure it in the image so I can use HTTPS in my wiki.

I noticed the image doesn't have Bitnami's bncert-tool so I tried to use the [alternative approach](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach), but the Lego script gives me a 'Error getting validation data' when I try to build the image.

Am I missing something here? Is this even the correct approach?

**Comment by cl3b34** [comment]
Just tried again by installing the bncert-tool in the image.
When I run the tool it asks for the directory containing the Bitnami Stack but it doesn't accept either of ` /bitnami ` or `/opt/bitnami` which seems to be the directories containing it.

**Comment by juan131** [comment]
Hi @cl3b34 

> I noticed the image doesn't have Bitnami's bncert-tool so I tried to use the alternative approach, but the Lego script gives me a 'Error getting validation data' when I try to build the image.
> Am I missing something here? Is this even the correct approach?

I'm afraid that guide is intended for the Bitnami VMs and native installers, but it doesn't apply for Bitnami containers.

To use custom SSL certificates on the container image, please refer to the instructions below:

- https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

**Comment by cl3b34** [comment]
I've seem that guide before, it assumes I have the certificate files.
With that, I either would not be able to use let's encrypt or would need to renew the certificate manually.
There is no way to use let's encrypt from within the container, with the automatic renewal then?

**Comment by juan131** [comment]
Hi @cl3b34 

> With that, I either would not be able to use let's encrypt or would need to renew the certificate manually. There is no way to use let's encrypt from within the container, with the automatic renewal then?

You could share a volume between the Dokuwiki container and another container that manages the TLS certificates generation/renewal (e.g. [cert-manager ](https://github.com/bitnami/bitnami-docker-cert-manager) or any custom container including Lego client). Sth like this (using Docker Compose):

```yaml
version: '2'

services:
  dokuwiki:
    image: docker.io/bitnami/dokuwiki:20200729
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
      - 'certs_data:/certs'
  cert-generator:
    image: YOUR-CUSTOM_IMAGE
    volumes:
      - 'certs_data:/certs'

volumes:
  dokuwiki_data:
    driver: local
  certs_data:
    driver: local
```
